Repository GhostyORG/Ghosty-web, pull requests merged in 2022-08, with the labels that each got.

#3 Addition of Projects Page
  about.html
  index.html
  projects.html
  res/css/custom/projects.min.css
  res/css/custom/projects.min.css.map
  res/js/projects.js
  res/scss/projects.scss
Labels: enhancement

#13 [Fix] Discord Link addition to all the pages of the site
  about.html
  members.html
  projects.html
Labels: bug

#14 Finalize the REACTJS transition with refactoring, style updates, documentations etc
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/data/Readme.md
  src/index.js
  src/pages/about.jsx
  src/pages/home.jsx
  src/pages/members.jsx
  src/pages/projects.jsx
  src/styles/css/custom/projects.min.css
  src/styles/css/custom/projects.min.css.map
  src/styles/scss/projects.scss
Labels: documentation, enhancement

#16 Footer Redesign
  src/components/Footer.jsx
  src/components/Header.jsx
  src/images/Discord-Logo-White.png
  src/images/globe.png
  src/styles/css/custom/footer.min.css
  src/styles/css/custom/footer.min.css.map
  src/styles/css/custom/index.min.css
  src/styles/css/custom/index.min.css.map
  src/styles/css/custom/variables.min.css
  src/styles/css/custom/variables.min.css.map
  src/styles/scss/footer.scss
  src/styles/scss/index.scss
  src/styles/scss/variables.scss
Labels: bug, enhancement

#17 Addition of a Error Page
  src/App.js
  src/pages/error.jsx
  src/styles/css/custom/error.min.css
  src/styles/css/custom/error.min.css.map
  src/styles/scss/error.scss
Labels: enhancement

#18 Addition of Dark and Light Mode feature
  docs/devNote.md
  package.json
  src/App.js
  src/components/Header.jsx
  src/images/dark_mode.png
  src/images/light_mode.png
  src/styles/css/custom/error.min.css
  src/styles/css/custom/error.min.css.map
  src/styles/css/custom/footer.min.css
  src/styles/css/custom/footer.min.css.map
  src/styles/css/custom/header.min.css
  src/styles/css/custom/header.min.css.map
  src/styles/css/custom/index.min.css
  src/styles/css/custom/index.min.css.map
  src/styles/css/custom/members.min.css
  src/styles/css/custom/members.min.css.map
  src/styles/css/custom/projects.min.css
  src/styles/css/custom/projects.min.css.map
  src/styles/css/custom/variables.min.css
  src/styles/css/custom/variables.min.css.map
  src/styles/scss/error.scss
  src/styles/scss/footer.scss
  src/styles/scss/header.scss
  src/styles/scss/index.scss
  src/styles/scss/members.scss
  src/styles/scss/projects.scss
  src/styles/scss/variables.scss
Labels: enhancement
